# shortcuts: seedClearAll
# desc: clears all firestore data
firebase firestore:delete -r -f authState &
firebase firestore:delete -r -f me &
firebase firestore:delete -r -f users &
firebase firestore:delete -r -f roles &
firebase firestore:delete -r -f appStateMixer &
firebase firestore:delete -r -f galleryState &
firebase firestore:delete -r -f blocksGalleryState &
firebase firestore:delete -r -f currentIds &
firebase firestore:delete -r -f libraryBlocks &
firebase firestore:delete -r -f libraryImages &
firebase firestore:delete -r -f libraryTypography &
firebase firestore:delete -r -f libraryPalettes &
firebase firestore:delete -r -f locales &
firebase firestore:delete -r -f packages &
firebase firestore:delete -r -f meta &
firebase firestore:delete -r -f palette &
firebase firestore:delete -r -f fontSizes &
firebase firestore:delete -r -f spacing &
firebase firestore:delete -r -f fonts &
firebase firestore:delete -r -f instancesBlocks &
firebase firestore:delete -r -f pages &
firebase firestore:delete -r -f images &
firebase firestore:delete -r -f locale &
firebase firestore:delete -r -f blocks &
firebase firestore:delete -r -f instancesMapColors &
firebase firestore:delete -r -f instancesMapStrings &
firebase firestore:delete -r -f instancesProps &
firebase firestore:delete -r -f strings &
firebase firestore:delete -r -f singles 
