export const items = [
  {
    id: 'personal',
    name: 'Personal',
    iconName: 'Seeding',
    width: 60,
  },
  {
    id: 'young_professionals',
    name: 'Professional',
    iconName: 'Tool',
    width: 85,
  },
  {
    id: 'hobbies',
    name: 'Hobbies & DIY',
    iconName: 'Palette',
    width: 96,
  },
  {
    id: 'urban_life',
    name: 'Urban life',
    iconName: 'BuildingCommunity',
    width: 64,
  },
  {
    id: 'movement',
    name: 'Movement',
    iconName: 'Bike',
    width: 69,
  },
  {
    id: 'information',
    name: 'Information',
    iconName: 'Wifi',
    width: 76,
  },
  {
    id: 'home',
    name: 'Apartment',
    iconName: 'Sofa',
    width: 70,
  },
  {
    id: 'life_directory',
    name: 'Life director',
    iconName: 'ChairDirector',
    width: 80,
  },
  {
    id: 'magical',
    name: 'Magical',
    iconName: 'Wand',
    width: 60,
  },
  {
    id: 'media',
    name: 'Media',
    iconName: 'BrandYoutube',
    width: 60,
  },
  {
    id: 'stores',
    name: 'Stores',
    iconName: 'BuildingStore',
    width: 60,
  },
  {
    id: 'data',
    name: 'Data',
    iconName: 'Database',
    width: 60,
  },
  {
    id: 'food',
    name: 'Food',
    iconName: 'Cup',
    width: 60,
  },
  {
    id: 'shopping',
    name: 'Shopping',
    iconName: 'ShoppingBag',
    width: 64,
  },
  {
    id: 'iot',
    name: 'IOT',
    iconName: 'AccessPoint',
    width: 60,
  },
  {
    id: 'integrations',
    name: 'Integrations',
    iconName: 'Affiliate',
    width: 79,
  },
  {
    id: 'top_installed',
    name: 'Top installed',
    iconName: 'Trophy',
    width: 85,
  },
  {
    id: 'editor_choice',
    name: 'Editor choice',
    iconName: 'Medal2',
    width: 88,
  },
];
