export const fields = {
  id: 'id',
  name: 'name',
  firstName: 'firstName',
  lastName: 'lastName',
  birthday: 'birthday',
  gender: 'gender',
  location: 'location',
  imageUrl: 'Photo',
  email: 'email',
  email2: 'email2',
  email3: 'email3',
  phone: 'phone',
  phone2: 'phone2',
  phone3: 'phone3',
  city: 'city',
  country: 'country',
  company: 'company',
  jobTitle: 'jobTitle',
  linkedin: 'linkedin',
  tier: 'tier',
};
