export const data = {
  projects: 5,
  caps: 1,
  keys: 0,
};

export const icons = [
  {
    id: 'contacts',
    name: 'Contacts',
    iconName: 'people',
    boardId: 'B-008',
    order: 1,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    iconName: 'calendar_month',
    boardId: 'B-009',
    order: 2,
  },
  {
    id: 'balance',
    name: 'Balance',
    iconName: 'balance',
    boardId: 'B-010',
    order: 3,
  },
  {
    id: 'finances',
    name: 'Finances',
    iconName: 'attach_money',
    boardId: 'B-011',
    order: 4,
  },
  {
    id: 'todos',
    name: 'Todos',
    iconName: 'task',
    boardId: 'B-012',
    order: 5,
  },
  {
    id: 'documents',
    name: 'Docs',
    iconName: 'description',
    boardId: 'B-013',
    order: 6,
  },
  {
    id: 'lists',
    name: 'Lists',
    iconName: 'notes',
    boardId: 'B-015',
    order: 7,
  },
  {
    id: 'events',
    name: 'Events',
    iconName: 'event',
    boardId: 'B-016',
    order: 8,
  },
  {
    id: 'locations',
    name: 'Locations',
    iconName: 'nature_people',
    boardId: 'B-027',
    order: 9,
  },
  {
    id: 'sales',
    name: 'Sales',
    iconName: 'point_of_sale',
    boardId: 'B-019',
    order: 10,
  },
  {
    id: 'books',
    name: 'Books',
    iconName: 'book',
    boardId: 'B-020',
    order: 11,
  },
  {
    id: 'movement',
    name: 'Movement',
    iconName: 'directions_bike',
    boardId: 'B-021',
    order: 12,
  },
  {
    id: 'post',
    name: 'Post',
    iconName: 'post_add',
    boardId: 'B-022',
    order: 13,
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    iconName: 'spa',
    boardId: 'B-023',
    order: 14,
  },
  {
    id: 'diy',
    name: 'DIY',
    iconName: 'build',
    boardId: 'B-024',
    order: 15,
  },
  {
    id: 'things',
    name: 'Things',
    iconName: 'editor_choice',
    boardId: 'B-025',
    order: 16,
  },
  {
    id: 'fun',
    name: 'Fun',
    iconName: 'sports_esports',
    boardId: 'B-026',
    order: 17,
  },
  {
    id: 'reminders',
    name: 'Reminders',
    iconName: 'alarm',
    boardId: 'B-052',
    order: 18,
  },
];
