export const formData: Json = {
    imageUrl: '',
    firstName: '',
    lastName: '',
    shortDescription: '',
    dateOfBirth: '2000-10-10',
    gender: '',
    tags: '',
    category: '',
    tier: '',
    company: '',
    jobTitle: '',
    height: '',
    socialFacebookUrl: '',
    socialTwitterUrl: '',
    socialInstagramUrl: '',
    socialLinkedInUrl: '',
    wikipediaUrl: '',
    email: '',
    netWorth: '',
    notes: '',
};
