import { IBarItems, IVoices } from './types';

export const voices: IVoices = {
  alloy: {
    id: 'alloy',
    title: 'Alloy',
    imageUrl: '/images/voices/voice_alloy.jpg',
    audioUrl: '/voices/voice-Alloy.mp3',
    provider: 'OpenAI',
  },
  echo: {
    id: 'echo',
    title: 'Echo',
    imageUrl: '/images/voices/voice_echo.jpg',
    audioUrl: '/voices/voice-Echo.mp3',
    provider: 'OpenAI',
  },
  fable: {
    id: 'fable',
    title: 'Fable',
    imageUrl: '/images/voices/voice_fable.jpg',
    audioUrl: '/voices/voice-Fable.mp3',
    provider: 'OpenAI',
  },
  onyx: {
    id: 'onyx',
    title: 'Onyx',
    imageUrl: '/images/voices/voice_onyx.jpg',
    audioUrl: '/voices/voice-Onyx.mp3',
    provider: 'OpenAI',
  },
  nova: {
    id: 'nova',
    title: 'Nova',
    imageUrl: '/images/voices/voice_nova.jpg',
    audioUrl: '/voices/voice-Nova.mp3',
    provider: 'OpenAI',
  },
  shimmer: {
    id: 'shimmer',
    title: 'Shimmer',
    imageUrl: '/images/voices/voice_shimmer.jpg',
    audioUrl: '/voices/voice-Shimmer.mp3',
    provider: 'OpenAI',
  },
  antoni: {
    id: 'antoni',
    title: 'Antoni',
    imageUrl: '/images/voices/voice_antoni.jpg',
    audioUrl: '/voices/voice-Antoni.mp3',
    provider: 'ElevenLabs',
    description: 'american, well-rounded, young, male, narration',
  },
  bella: {
    id: 'bella',
    title: 'Bella',
    imageUrl: '/images/voices/voice_bella.jpg',
    audioUrl: '/voices/voice-Bella.mp3',
    provider: 'ElevenLabs',
    description: 'american, soft, young, female, narration',
  },
  bill: {
    id: 'bill',
    title: 'Bill',
    imageUrl: '/images/voices/voice_bill.jpg',
    audioUrl: '/voices/voice-Bill.mp3',
    provider: 'ElevenLabs',
    description: 'american, strong, middle aged, male, documentary',
  },
  callum: {
    id: 'callum',
    title: 'Callum',
    imageUrl: '/images/voices/voice_callum.jpg',
    audioUrl: '/voices/voice-Callum.mp3',
    provider: 'ElevenLabs',
    description: 'american, hoarse, middle aged, male, video games',
  },
  charlie: {
    id: 'charlie',
    title: 'Charlie',
    imageUrl: '/images/voices/voice_charlie.jpg',
    audioUrl: '/voices/voice-Charlie.mp3',
    provider: 'ElevenLabs',
    description: 'australian, casual, middle aged, male, conversational',
  },
  clyde: {
    id: 'clyde',
    title: 'Clyde',
    imageUrl: '/images/voices/voice_clyde.jpg',
    audioUrl: '/voices/voice-Clyde.mp3',
    provider: 'ElevenLabs',
    description: 'american, war veteran, middle aged, male, video games',
  },
  domi: {
    id: 'domi',
    title: 'Domi',
    imageUrl: '/images/voices/voice_domi.jpg',
    audioUrl: '/voices/voice-Domi.mp3',
    provider: 'ElevenLabs',
    description: 'american, strong, young, female, narration',
  },
  dorothy: {
    id: 'dorothy',
    title: 'Dorothy',
    imageUrl: '/images/voices/voice_dorothy.jpg',
    audioUrl: '/voices/voice-Dorothy.mp3',
    provider: 'ElevenLabs',
    description: "british, pleasant, young, female, children's stories",
  },
  freya: {
    id: 'freya',
    title: 'Freya',
    imageUrl: '/images/voices/voice_freya.jpg',
    audioUrl: '/voices/voice-Freya.mp3',
    provider: 'ElevenLabs',
    description: 'american, young, female, overhyped, video games',
  },
  george: {
    id: 'george',
    title: 'George',
    imageUrl: '/images/voices/voice_george.jpg',
    audioUrl: '/voices/voice-George.mp3',
    provider: 'ElevenLabs',
    description: 'british, raspy, middle aged, male, narration',
  },
  giovanni: {
    id: 'giovanni',
    title: 'Giovanni',
    imageUrl: '/images/voices/voice_giovanni.jpg',
    audioUrl: '/voices/voice-Giovanni.mp3',
    provider: 'ElevenLabs',
    description: 'english-italian, foreigner, young, male, audiobook',
  },
  grace: {
    id: 'grace',
    title: 'Grace',
    imageUrl: '/images/voices/voice_grace.jpg',
    audioUrl: '/voices/voice-Grace.mp3',
    provider: 'ElevenLabs',
    description: 'american-southern, young, female, audiobook , gentle',
  },
  harry: {
    id: 'harry',
    title: 'Harry',
    imageUrl: '/images/voices/voice_harry.jpg',
    audioUrl: '/voices/voice-Harry.mp3',
    provider: 'ElevenLabs',
    description: 'american, anxious, young, male, video games',
  },
  james: {
    id: 'james',
    title: 'James',
    imageUrl: '/images/voices/voice_james.jpg',
    audioUrl: '/voices/voice-James.mp3',
    provider: 'ElevenLabs',
    description: 'australian, calm , old, male, news',
  },
  josh: {
    id: 'josh',
    title: 'Josh',
    imageUrl: '/images/voices/voice_josh.jpg',
    audioUrl: '/voices/voice-Josh.mp3',
    provider: 'ElevenLabs',
    description: 'american, deep, young, male, narration',
  },
  liam: {
    id: 'liam',
    title: 'Liam',
    imageUrl: '/images/voices/voice_liam.jpg',
    audioUrl: '/voices/voice-Liam.mp3',
    provider: 'ElevenLabs',
    description: 'american, young, male, narration, neutral',
  },
  matilda: {
    id: 'matilda',
    title: 'Matilda',
    imageUrl: '/images/voices/voice_matilda.jpg',
    audioUrl: '/voices/voice-Matilda.mp3',
    provider: 'ElevenLabs',
    description: 'american, warm, young, female, audiobook',
  },
  mimi: {
    id: 'mimi',
    title: 'Mimi',
    imageUrl: '/images/voices/voice_mimi.jpg',
    audioUrl: '/voices/voice-Mimi.mp3',
    provider: 'ElevenLabs',
    description: 'english-swedish, childish, young, female, animation',
  },
  nicole: {
    id: 'nicole',
    title: 'Nicole',
    imageUrl: '/images/voices/voice_nicole.jpg',
    audioUrl: '/voices/voice-Nicole.mp3',
    provider: 'ElevenLabs',
    description: 'american, whisper, young, female, audiobook',
  },
  paul: {
    id: 'paul',
    title: 'Paul',
    imageUrl: '/images/voices/voice_paul.jpg',
    audioUrl: '/voices/voice-Paul.mp3',
    provider: 'ElevenLabs',
    description: 'american, ground reporter, middle aged, male, news',
  },
};
