export const itemStructure = `export type IProduct = {
    id: string;
    title: string;
    startDate: string;
    productType: IProductType;
    status: IProductStatus;
    statusDate: string;
    endDate?: string;
    description: string;
    personId: string;
    nextVisitDate: string;
    items: IProductJournal[];
    worth?: number;
    percent?: number;
    isArchived?: boolean;
    isSuccessful?: boolean;
    isLost?: boolean;
    tags: string[];
    dataTags: string[];
};
`;
