export default {
    meta: {
        schemaVersion: '1.0.1',
    },
    appStateMixer: {
        stateKey: 'mixer',
        mode: 'structure',
        selectedToolId: 'browse',
        paletteId: 'blue',
    },
    currentIds: {
        pageId: 'home',
        selectedInstanceId: '',
        contentInstanceId: '',
        libraryInstanceId: '',
    },
    locale: {
        localeId: 'en',
        isRtl: false,
    },
    palette: {
        themeDarker: '#004578',
        themeDark: '#005a9e',
        themeDarkAlt: '#106ebe',
        themePrimary: '#0078d4',
        themeSecondary: '#2b88d8',
        themeTertiary: '#71afe5',
        themeLight: '#c7e0f4',
        themeLighter: '#deecf9',
        themeLighterAlt: '#eff6fc',
        black: '#000000',
        blackTranslucent40: 'rgba(0,0,0,.4)',
        neutralDark: '#201f1e',
        neutralPrimary: '#323130',
        neutralPrimaryAlt: '#3b3a39',
        neutralSecondary: '#605e5c',
        neutralSecondaryAlt: '#8a8886',
        neutralTertiary: '#a19f9d',
        neutralTertiaryAlt: '#c8c6c4',
        neutralQuaternary: '#d2d0ce',
        neutralQuaternaryAlt: '#e1dfdd',
        neutralLight: '#edebe9',
        neutralLighter: '#f3f2f1',
        neutralLighterAlt: '#faf9f8',
        accent: '#0078d4',
        white: '#ffffff',
        whiteTranslucent40: 'rgba(255,255,255,.4)',
        yellowDark: '#d29200',
        yellow: '#ffb900',
        yellowLight: '#fff100',
        orange: '#d83b01',
        orangeLight: '#ea4300',
        orangeLighter: '#ff8c00',
        redDark: '#a4262c',
        red: '#e81123',
        magentaDark: '#5c005c',
        magenta: '#b4009e',
        magentaLight: '#e3008c',
        purpleDark: '#32145a',
        purple: '#5c2d91',
        purpleLight: '#b4a0ff',
        blueDark: '#002050',
        blueMid: '#00188f',
        blue: '#0078d4',
        blueLight: '#00bcf2',
        tealDark: '#004b50',
        teal: '#008272',
        tealLight: '#00b294',
        greenDark: '#004b1c',
        green: '#107c10',
        greenLight: '#bad80a',
    },
    fontSizes: {
        tiny: '10px',
        xSmall: '10px',
        small: '12px',
        smallPlus: '12px',
        medium: '14px',
        mediumPlus: '16px',
        icon: '16px',
        large: '18px',
        xLarge: '20px',
        xLargePlus: '24px',
        xxLarge: '28px',
        xxLargePlus: '32px',
        superLarge: '42px',
        mega: '68px',
    },
    spacing: {
        s1: '4px',
        s2: '8px',
        m: '16px',
        l1: '20px',
        l2: '32px',
    },
    fonts: {
        typographyId: 'Inter',
        fontFamily: "'Inter', sans-serif",
        fontWeight: 'regular',
    },
    instances: {
        'home-hero-simple-1': {
            id: 'home-hero-simple-1',
            widgetId: 'com.usegdi.templates.gdi.hero-simple',
            pageId: 'home',
            order: 1,
        },
        'home-threePoints-simple-1': {
            id: 'home-threePoints-simple-1',
            widgetId: 'com.usegdi.templates.gdi.threePoints-simple',
            pageId: 'home',
            order: 2,
        },
        'home-userBar-simple-1': {
            id: 'home-userBar-simple-1',
            widgetId: 'com.usegdi.templates.gdi.userBar-simple',
            pageId: 'home',
            order: 3,
        },
        'home-textAndImage-simple-1': {
            id: 'home-textAndImage-simple-1',
            widgetId: 'com.usegdi.templates.gdi.textAndImage-simple',
            pageId: 'home',
            order: 4,
        },
        'home-hero-lineCta-1': {
            id: 'home-hero-lineCta-1',
            widgetId: 'com.usegdi.templates.gdi.lineCta-simple',
            pageId: 'home',
            order: 5,
        },
        'home-footer-simple-1': {
            id: 'home-footer-simple-1',
            widgetId: 'com.usegdi.templates.gdi.footer-simple',
            pageId: 'home',
            order: 6,
        },
    },
    widgets: {
        'com.usegdi.templates.gdi.hero-simple': {
            id: 'com.usegdi.templates.gdi.hero-simple',
            name: '',
            description: '',
            defaultDimension: { x: 10, y: 10 },
            tags: ['type-hero'],
        },
        'com.usegdi.templates.gdi.threePoints-simple': {
            id: 'com.usegdi.templates.gdi.threePoints-simple',
            name: '',
            description: '',
            defaultDimension: { x: 10, y: 10 },
            tags: ['type-threePoints'],
        },
        'com.usegdi.templates.gdi.userBar-simple': {
            id: 'com.usegdi.templates.gdi.userBar-simple',
            name: '',
            description: '',
            defaultDimension: { x: 10, y: 10 },
            tags: ['type-userBar'],
        },
        'com.usegdi.templates.gdi.textAndImage-simple': {
            id: 'com.usegdi.templates.gdi.textAndImage-simple',
            name: '',
            description: '',
            defaultDimension: { x: 10, y: 10 },
            tags: ['type-textAndImage'],
        },
        'com.usegdi.templates.gdi.lineCta-simple': {
            id: 'com.usegdi.templates.gdi.lineCta-simple',
            name: '',
            description: '',
            defaultDimension: { x: 10, y: 10 },
            tags: ['type-lineCta'],
        },
        'com.usegdi.templates.gdi.footer-simple': {
            id: 'com.usegdi.templates.gdi.footer-simple',
            name: '',
            description: '',
            defaultDimension: { x: 10, y: 10 },
            tags: ['type-footer'],
        },
    },
    instancesMapColors: {},
    instancesMapStrings: {},
    instancesProps: {},
    pages: {
        home: {
            id: 'home',
            title: 'Home',
            description: 'The home page',
            iconName: 'Home',
            order: 1,
        },
    },
    strings: {
        en_good: '',
    },
    library: {},
    typographyLibrary: {
        andadaPro: {
            id: 'andadaPro',
            title: 'Andada Pro',
            fontFamily: "'Andada Pro', serif",
            link: 'Andada+Pro:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400;1,500;1,600;1,700;1,800',
        },
        encodeSans: {
            id: 'encodeSans',
            title: 'EncodeSans',
            fontFamily: "'Encode Sans', sans-serif",
            link: 'Encode+Sans:wght@100;200;300;400;500;600;700;800;900',
        },
        epilogue: {
            id: 'epilogue',
            title: 'Epilogue',
            fontFamily: "'Epilogue', sans-serif",
            link: 'Epilogue:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900',
        },
        hamlet: {
            id: 'hamlet',
            title: 'Hamlet',
            fontFamily: "'Hahmlet', serif",
            link: 'Hahmlet:wght@100;200;300;400;500;600;700;800;900',
        },
        inter: {
            id: 'inter',
            title: 'Inter',
            fontFamily: "'Inter', sans-serif",
            link: 'Inter:wght@100;200;300;400;500;600;700;800;900',
        },
        jetBrainsMono: {
            id: 'jetBrainsMono',
            title: 'JetBrains Mono',
            fontFamily: "'Hahmlet', serif",
            link: 'JetBrains+Mono:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800',
        },
        manrope: {
            id: 'manrope',
            title: 'Manrope',
            fontFamily: "'Manrope', sans-serif",
            link: 'Manrope:wght@200;300;400;500;600;700;800',
        },
        lora: {
            id: 'lora',
            title: 'Lora',
            fontFamily: "'Lora', serif",
            link: 'Lora:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700',
        },
        sora: {
            id: 'sora',
            title: 'Sora',
            fontFamily: "'Sora', sans-serif",
            link: 'Sora:wght@100;200;300;400;500;600;700;800',
        },
    },
    palettesLibrary: {
        blue: {
            id: 'blue',
            title: 'Blue',
            color1: '#1d3557',
            color2: '#457b9d',
            color3: '#a8dadc',
            color4: '#f1faee',
            color5: '#e63946',
        },
        green: {
            id: 'green',
            title: 'Green',
            color1: '#22577a',
            color2: '#38a3a5',
            color3: '#57cc99',
            color4: '#80ed99',
            color5: '#c7f9cc',
        },
    },
    locales: {
        en: {
            id: 'en',
            title: 'English',
        },
    },
    packages: {
        '@gdi/template-gdi': '0.0.2',
        '@gdi/store-business-base': '0.0.1',
    },
};
