import { IWidgetInstancesByPageList } from '@gdi/platformer';
import { StudioWidgets } from './widgets';
import { SoundboardWidgets } from '@gdi/app-soundboard';
import { TasksWidgets } from '@gdi/app-tasks';

export const instances: IWidgetInstancesByPageList = {
    babylon: [
        {
            id: '3',
            widgetId: StudioWidgets.Babylon,
            position: { y: 2, x: 3 },
            dimension: { y: 46, x: 128 },
            isTransparent: true,
        },

        {
            id: '5',
            widgetId: SoundboardWidgets.Sims,
            position: { y: 9, x: 7 },
            dimension: { y: 10, x: 12 },
            isTransparent: true,
            flavour: 'main',
            isHidden: true,
        },
        {
            id: '6',
            widgetId: StudioWidgets.Schedule,
            position: { y: 17, x: 7 },
            dimension: { y: 5, x: 15 },
            flavour: 'main',
            isTransparent: true,
            isHidden: true,
        },
        {
            id: '7',
            widgetId: TasksWidgets.Mini,
            position: { y: 37, x: 7 },
            dimension: { y: 8, x: 14 },
            isTransparent: true,
            isHidden: true,
        },
        {
            id: '8',
            widgetId: SoundboardWidgets.ScheduleClock2,
            position: { y: 3, x: 108 },
            dimension: { y: 6, x: 22 },
            isTransparent: true,
            flavour: 'main',
            isHidden: true,
        },
        {
            id: '9',
            widgetId: StudioWidgets.Poe,
            position: { y: 39, x: 22 },
            dimension: { y: 6, x: 36 },
            isTransparent: true,
            flavour: 'main',
            isHidden: true,
        },
        {
            id: '10',
            widgetId: SoundboardWidgets.Mini,
            position: { y: 39, x: 59 },
            dimension: { y: 6, x: 14 },
            flavour: 'main',
            isHidden: true,
        },
        {
            id: '11',
            widgetId: StudioWidgets.IsoBrowser,
            position: { y: 3, x: 78 },
            dimension: { y: 24, x: 20 },
            isTransparent: true,
            flavour: 'main',
            isHidden: true,
        },
        {
            id: '12',
            widgetId: StudioWidgets.Ideas,
            position: { y: 3, x: 99 },
            dimension: { y: 24, x: 23 },
            isTransparent: true,
            flavour: 'second',
            isHidden: true,
        },
        {
            id: '13',
            widgetId: StudioWidgets.Switcher,
            position: { y: 3, x: 18 },
            dimension: { y: 2, x: 16 },
            isTransparent: true,
            flavour: 'main',
            isHidden: true,
        },
        {
            id: '14',
            widgetId: StudioWidgets.Rating,
            position: { y: 9, x: 7 },
            dimension: { y: 8, x: 12 },
            isTransparent: true,
            flavour: 'building',
            isHidden: true,
        },
        {
            id: '15',
            widgetId: StudioWidgets.DomainHeader,
            position: { y: 3, x: 22 },
            dimension: { y: 6, x: 36 },
            isTransparent: true,
            flavour: 'building',
            isHidden: true,
        },
        {
            id: '16',
            widgetId: StudioWidgets.DomainPanel,
            position: { y: 39, x: 22 },
            dimension: { y: 6, x: 36 },
            isTransparent: true,
            flavour: 'building',
            isHidden: true,
        },
        {
            id: '17',
            widgetId: StudioWidgets.DomainHistory,
            position: { y: 18, x: 7 },
            dimension: { y: 5, x: 15 },
            isTransparent: true,
            flavour: 'building',
            isHidden: true,
        },
        {
            id: '18',
            widgetId: StudioWidgets.ProTip,
            position: { y: 32, x: 59 },
            dimension: { y: 13, x: 17 },
            isTransparent: true,
            flavour: 'building',
            isHidden: true,
        },
        {
            id: '19',
            widgetId: StudioWidgets.Legend,
            position: { y: 9, x: 19 },
            dimension: { y: 5, x: 12 },
            isTransparent: true,
            flavour: 'building',
            isHidden: true,
        },
    ],
};
