import { devtools } from '@gdi/store-devtools';
import { selectors as allSelectors } from '../store';
import { createSelector } from 'reselect';

export const selectors = devtools;

export const $allOptions = createSelector(
    allSelectors.options.auth.$allOptions,
    allSelectors.options.mixer.$allOptions,
    allSelectors.options.site.$allOptions,
    allSelectors.options.factory.$allOptions,
    allSelectors.options.dashboard.$allOptions,
    allSelectors.options.settings.$allOptions,
    allSelectors.options.biblo.$allOptions,
    allSelectors.options.carts.$allOptions,
    allSelectors.options.comments.$allOptions,
    allSelectors.options.campaigns.$allOptions,
    allSelectors.options.devtools.$allOptions,
    allSelectors.options.events.$allOptions,
    allSelectors.options.knowledge.$allOptions,
    allSelectors.options.leads.$allOptions,
    allSelectors.options.money.$allOptions,
    allSelectors.options.orders.$allOptions,
    allSelectors.options.ppl.$allOptions,
    allSelectors.options.products.$allOptions,
    allSelectors.options.sales.$allOptions,
    allSelectors.options.soundboard.$allOptions,
    allSelectors.options.studio.$allOptions,
    allSelectors.options.tasks.$allOptions,
    allSelectors.options.things.$allOptions,
    allSelectors.options.voice.$allOptions,
    allSelectors.options.weather.$allOptions,
    (
        auth,
        mixer,
        site,
        factory,
        dashboard,
        settings,
        biblo,
        carts,
        comments,
        campaigns,
        devtools,
        events,
        knowledge,
        leads,
        money,
        orders,
        ppl,
        products,
        sales,
        soundboard,
        studio,
        tasks,
        things,
        voice,
        weather
    ) => {
        return {
            auth,
            mixer,
            site,
            factory,
            dashboard,
            settings,
            biblo,
            carts,
            comments,
            campaigns,
            devtools,
            events,
            knowledge,
            leads,
            money,
            orders,
            ppl,
            products,
            sales,
            soundboard,
            studio,
            tasks,
            things,
            voice,
            weather,
        };
    }
);
