import * as path from 'path';
import { aliasExtra } from './vite.extra';

const cwd = path.resolve(process.cwd(), '../../');

export const alias = {
    '@gdi/app-login': `${cwd}/apps/app-login/src`,
    '@gdi/app-mixer': `${cwd}/apps/app-mixer/src`,
    '@gdi/app-factory': `${cwd}/apps/app-factory/src`,
    '@gdi/app-settings': `${cwd}/apps/app-settings/src`,
    '@gdi/app-dashboard': `${cwd}/apps/app-dashboard/src`,

    '@gdi/store-auth': `${cwd}/stores/gdi-store-auth/src`,
    '@gdi/store-mixer': `${cwd}/stores/gdi-store-mixer/src`,
    '@gdi/store-site': `${cwd}/stores/gdi-store-site/src`,
    '@gdi/store-factory': `${cwd}/stores/gdi-store-factory/src`,
    '@gdi/store-dashboard': `${cwd}/stores/gdi-store-dashboard/src`,
    '@gdi/store-settings': `${cwd}/stores/gdi-store-settings/src`,

    '@gdi/template-starter': `${cwd}/packages/gdi-template-starter/src`,
    '@gdi/platformer': `${cwd}/packages/platformer/src`,
    '@gdi/web-base-ui': `${cwd}/packages/gdi-web-base-ui/src`,
    '@gdi/web-ui': `${cwd}/packages/gdi-web-ui/src`,
    '@gdi/web-tables': `${cwd}/packages/gdi-web-tables/src`,
    '@gdi/web-forms': `${cwd}/packages/gdi-web-forms/src`,
    '@gdi/web-editors': `${cwd}/packages/gdi-web-editors/src`,
    '@gdi/hooks': `${cwd}/packages/gdi-hooks/src`,
    '@gdi/engine': `${cwd}/packages/gdi-engine/src`,

    '@gdi/app-biblo': `${cwd}/extra/apps/app-biblo/src`,
    '@gdi/app-carts': `${cwd}/extra/apps/app-carts/src`,
    '@gdi/app-devtools': `${cwd}/extra/apps/app-devtools/src`,
    '@gdi/app-events': `${cwd}/extra/apps/app-events/src`,
    '@gdi/app-knowledge': `${cwd}/extra/apps/app-knowledge/src`,
    '@gdi/app-money': `${cwd}/extra/apps/app-money/src`,
    '@gdi/app-orders': `${cwd}/extra/apps/app-orders/src`,
    '@gdi/app-ppl': `${cwd}/extra/apps/app-ppl/src`,
    '@gdi/app-products': `${cwd}/extra/apps/app-products/src`,
    '@gdi/app-sales': `${cwd}/extra/apps/app-sales/src`,
    '@gdi/app-soundboard': `${cwd}/extra/apps/app-soundboard/src`,
    '@gdi/app-studio': `${cwd}/extra/apps/app-studio/src`,
    '@gdi/app-tasks': `${cwd}/extra/apps/app-tasks/src`,
    '@gdi/app-things': `${cwd}/extra/apps/app-things/src`,
    '@gdi/app-voice': `${cwd}/extra/apps/app-voice/src`,
    '@gdi/store-biblo': `${cwd}/extra/stores/gdi-store-biblo/src`,
    '@gdi/store-carts': `${cwd}/extra/stores/gdi-store-carts/src`,
    '@gdi/store-devtools': `${cwd}/extra/stores/gdi-store-devtools/src`,
    '@gdi/store-events': `${cwd}/extra/stores/gdi-store-events/src`,
    '@gdi/store-knowledge': `${cwd}/extra/stores/gdi-store-knowledge/src`,
    '@gdi/store-money': `${cwd}/extra/stores/gdi-store-money/src`,
    '@gdi/store-orders': `${cwd}/extra/stores/gdi-store-orders/src`,
    '@gdi/store-ppl': `${cwd}/extra/stores/gdi-store-ppl/src`,
    '@gdi/store-products': `${cwd}/extra/stores/gdi-store-products/src`,
    '@gdi/store-sales': `${cwd}/extra/stores/gdi-store-sales/src`,
    '@gdi/store-soundboard': `${cwd}/extra/stores/gdi-store-soundboard/src`,
    '@gdi/store-studio': `${cwd}/extra/stores/gdi-store-studio/src`,
    '@gdi/store-tasks': `${cwd}/extra/stores/gdi-store-tasks/src`,
    '@gdi/store-things': `${cwd}/extra/stores/gdi-store-things/src`,
    '@gdi/store-voice': `${cwd}/extra/stores/gdi-store-voice/src`,
    '@gdi/store-weather': `${cwd}/extra/stores/gdi-store-weather/src`,

    'redux-connected': `${cwd}/submodules/redux-connected/src`,
    'shared-base': `${cwd}/submodules/shared-base/src`,
    '@gdi/dnd': `${cwd}/submodules/gdi-dnd/src`,
    'redux-connected-devtools': `${cwd}/submodules/redux-connected-devtools/src`,
    'redux-store-generator': `${cwd}/submodules/redux-store-generator/src`,
    igrid: `${cwd}/submodules/igrid/src`,
    isokit: `${cwd}/submodules/isokit/src`,
    firestore: `${cwd}/submodules/firestore-local/src`,
    '@gdi/language': `${cwd}/packages/gdi-language/src`,
    '@gdi/language-en': `${cwd}/packages/gdi-language-en/src`,
    ...aliasExtra,
};
