export const mainKeys = [
  { id: 'q', value: 'q' },
  { id: 'w', value: 'w' },
  { id: 'e', value: 'e' },
  { id: 'r', value: 'r' },
  { id: 't', value: 't' },
  { id: 'y', value: 'y' },
  { id: 'u', value: 'u' },
  { id: 'i', value: 'i' },
  { id: 'o', value: 'o' },
  { id: 'p', value: 'p' },
  { id: 'a', value: 'a', marginLeft: 30 },
  { id: 's', value: 's' },
  { id: 'd', value: 'd' },
  { id: 'f', value: 'f' },
  { id: 'g', value: 'g' },
  { id: 'h', value: 'h' },
  { id: 'j', value: 'j' },
  { id: 'k', value: 'k' },
  { id: 'l', value: 'l' },
  { id: 'shift', value: 'shift', iconName: 'shift', isModifier: true },
  { id: 'z', value: 'z', marginLeft: 9 },
  { id: 'x', value: 'x' },
  { id: 'c', value: 'c' },
  { id: 'v', value: 'v' },
  { id: 'b', value: 'b' },
  { id: 'n', value: 'n' },
  { id: 'm', value: 'm' },
  {
    id: 'backspace',
    value: 'backspace',
    iconName: 'backspace',
    isModifier: true,
    marginLeft: 9,
  },
];

export const bottomKeys = [
  { id: 'numeric', value: '123', isModifier: true },
  { id: 'emojis', value: 'emojis', iconName: 'sentiment_very_satisfied', isModifier: true },
  { id: 'space', value: 'space' },
  { id: 'return', value: 'return', isModifier: true },
];
