import { filters } from './filters';
import { formsEdit, formsNew, formsNewDefault } from './forms';
import { tables } from './tables';
import { galleries } from './galleries';
import { timelines } from './timelines';
import { calendars } from './calendars';
import { sheets } from './sheets';
import { overlays } from './overlays';
import { itemStructure } from './item';
import { ICrudDefinitions } from '../types';

export const definitions: Record<string, ICrudDefinitions> = {
    article: {
        nodeName: 'articles',
        filters: filters.article,
        formNew: formsNew.article,
        formNewDefault: formsNewDefault.article,
        formEdit: formsEdit.article,
        table: tables.article,
        gallery: galleries.article,
        calendar: calendars.article,
        timeline: timelines.article,
        sheet: sheets.article,
        overlay: overlays.article,
        itemStructure: itemStructure.article,
    },
    event: {
        nodeName: 'events',
        filters: filters.event,
        formNew: formsNew.event,
        formNewDefault: formsNewDefault.event,
        formEdit: formsEdit.event,
        table: tables.event,
        gallery: galleries.event,
        calendar: calendars.event,
        timeline: timelines.event,
        sheet: sheets.event,
        overlay: overlays.event,
        itemStructure: itemStructure.event,
    },
    image: {
        nodeName: 'images',
        filters: filters.image,
        formNew: formsNew.image,
        formNewDefault: formsNewDefault.image,
        formEdit: formsEdit.image,
        table: tables.image,
        gallery: galleries.image,
        calendar: calendars.image,
        timeline: timelines.image,
        sheet: sheets.image,
        overlay: overlays.image,
        itemStructure: itemStructure.image,
    },
    inbox: {
        nodeName: 'inbox',
        filters: filters.inbox,
        formNew: formsNew.inbox,
        formNewDefault: formsNewDefault.inbox,
        formEdit: formsEdit.inbox,
        table: tables.inbox,
        gallery: galleries.inbox,
        calendar: calendars.inbox,
        timeline: timelines.inbox,
        sheet: sheets.inbox,
        overlay: overlays.inbox,
        itemStructure: itemStructure.inbox,
    },
    layout: {
        nodeName: 'layouts',
        filters: filters.layout,
        formNew: formsNew.layout,
        formNewDefault: formsNewDefault.layout,
        formEdit: formsEdit.layout,
        table: tables.layout,
        gallery: galleries.layout,
        calendar: calendars.layout,
        timeline: timelines.layout,
        sheet: sheets.layout,
        overlay: overlays.layout,
        itemStructure: itemStructure.layout,
    },
    link: {
        nodeName: 'links',
        filters: filters.link,
        formNew: formsNew.link,
        formNewDefault: formsNewDefault.link,
        formEdit: formsEdit.link,
        table: tables.link,
        gallery: galleries.link,
        calendar: calendars.link,
        timeline: timelines.link,
        sheet: sheets.link,
        overlay: overlays.link,
        itemStructure: itemStructure.link,
    },
    page: {
        nodeName: 'pages',
        filters: filters.page,
        formNew: formsNew.page,
        formNewDefault: formsNewDefault.page,
        formEdit: formsEdit.page,
        table: tables.page,
        gallery: galleries.page,
        calendar: calendars.page,
        timeline: timelines.page,
        sheet: sheets.page,
        overlay: overlays.page,
        itemStructure: itemStructure.page,
    },
    pageInstance: {
        nodeName: 'pages',
        filters: filters.pageInstance,
        formNew: formsNew.pageInstance,
        formNewDefault: formsNewDefault.pageInstance,
        formEdit: formsEdit.pageInstance,
        table: tables.pageInstance,
        gallery: galleries.pageInstance,
        calendar: calendars.pageInstance,
        timeline: timelines.pageInstance,
        sheet: sheets.pageInstance,
        overlay: overlays.pageInstance,
        itemStructure: itemStructure.pageInstance,
    },
    post: {
        nodeName: 'posts',
        filters: filters.post,
        formNew: formsNew.post,
        formNewDefault: formsNewDefault.post,
        formEdit: formsEdit.post,
        table: tables.post,
        gallery: galleries.post,
        calendar: calendars.post,
        timeline: timelines.post,
        sheet: sheets.post,
        overlay: overlays.post,
        itemStructure: itemStructure.post,
    },
    person: {
        nodeName: 'persons',
        filters: filters.person,
        formNew: formsNew.person,
        formNewDefault: formsNewDefault.person,
        formEdit: formsEdit.person,
        table: tables.person,
        gallery: galleries.person,
        calendar: calendars.person,
        timeline: timelines.person,
        sheet: sheets.person,
        overlay: overlays.person,
        itemStructure: itemStructure.person,
    },
    project: {
        nodeName: 'projects',
        filters: filters.project,
        formNew: formsNew.project,
        formNewDefault: formsNewDefault.project,
        formEdit: formsEdit.project,
        table: tables.project,
        gallery: galleries.project,
        calendar: calendars.project,
        timeline: timelines.project,
        sheet: sheets.project,
        overlay: overlays.project,
        itemStructure: itemStructure.project,
    },
    sale: {
        nodeName: 'sales',
        filters: filters.sale,
        formNew: formsNew.sale,
        formNewDefault: formsNewDefault.sale,
        formEdit: formsEdit.sale,
        table: tables.sale,
        gallery: galleries.sale,
        calendar: calendars.sale,
        timeline: timelines.sale,
        sheet: sheets.sale,
        overlay: overlays.sale,
        itemStructure: itemStructure.sale,
    },
    template: {
        nodeName: 'templates',
        filters: filters.template,
        formNew: formsNew.template,
        formNewDefault: formsNewDefault.template,
        formEdit: formsEdit.template,
        table: tables.template,
        gallery: galleries.template,
        calendar: calendars.template,
        timeline: timelines.template,
        sheet: sheets.template,
        overlay: overlays.template,
        itemStructure: itemStructure.template,
    },
    ticket: {
        nodeName: 'tickets',
        filters: filters.ticket,
        formNew: formsNew.ticket,
        formNewDefault: formsNewDefault.ticket,
        formEdit: formsEdit.ticket,
        table: tables.ticket,
        gallery: galleries.ticket,
        calendar: calendars.ticket,
        timeline: timelines.ticket,
        sheet: sheets.ticket,
        overlay: overlays.ticket,
        itemStructure: itemStructure.ticket,
    },
    widget: {
        nodeName: 'widgets',
        filters: filters.widget,
        formNew: formsNew.widget,
        formNewDefault: formsNewDefault.widget,
        formEdit: formsEdit.widget,
        table: tables.widget,
        gallery: galleries.widget,
        calendar: calendars.widget,
        timeline: timelines.widget,
        sheet: sheets.widget,
        overlay: overlays.widget,
        itemStructure: itemStructure.widget,
    },
};
