import { PhoneMenu } from '@gdi/ui';
import type { IMenuItem } from '@gdi/ui';

export const MenuContainer = () => {
  return <PhoneMenu data={items} groups={groups} />;
};

const items: IMenuItem[] = [
  {
    path: '/admin/campaigns',
    icon: 'campaign',
    label: 'Advertise',
    groupId: 'marketing',
    order: 1,
  },
  {
    path: '/admin/carts',
    icon: 'shopping_cart',
    label: 'Carts',
    groupId: 'shop',
    order: 3,
  },
  {
    path: '/admin/comments',
    icon: 'comment',
    label: 'Comment',
    groupId: 'site',
    order: 1.5,
  },
  {
    path: '/admin/overview',
    icon: 'inbox',
    label: 'Inbox',
    groupId: 'doing',
    showOnSlim: true,
    order: 0.5,
  },
  {
    path: '/admin/deals',
    icon: 'bolt',
    label: 'Deals',
    groupId: 'marketing',
    order: 3,
  },
  {
    path: '/admin/docs/home',
    icon: 'description',
    label: 'Docs',
    groupId: 'site',
    showOnSlim: true,
    order: 0,
  },
  {
    path: '/admin/events',
    icon: 'event',
    label: 'Events',
    groupId: 'extra',
    order: 0,
  },
  {
    path: '/admin/reminders',
    icon: 'alarm',
    label: 'Remind',
    groupId: 'extra',
    order: 0,
  },
  {
    path: '/admin/factory/articles',
    icon: 'article',
    label: 'Articles',
    groupId: 'site',
    order: 1,
  },
  {
    path: '/admin/factory/layouts',
    icon: 'view_comfy',
    label: 'Layouts',
    groupId: 'extra',
    order: 1.5,
  },
  {
    path: '/admin/factory/customWidgets',
    icon: 'trolley',
    label: 'Widgets',
    groupId: 'site',
    order: 2,
  },
  {
    path: '/admin/knowledge',
    icon: 'bookmarks',
    label: 'Links',
    groupId: 'doing',
    order: 5,
  },
  {
    path: '/admin/leads',
    icon: 'wifi_tethering',
    label: 'Leads',
    groupId: 'marketing',
    order: 2,
  },
  {
    path: '/admin/pages',
    icon: 'format_paint',
    label: 'Mixer',
    groupId: 'site',
    showOnSlim: true,
    order: 0,
  },
  {
    path: '/admin/imageGallery',
    icon: 'gallery_thumbnail',
    label: 'Images',
    groupId: 'site',
    order: 1,
  },
  {
    path: '/admin/widgetGallery',
    icon: 'grid_view',
    label: 'Blocks',
    groupId: 'site',
    order: 2,
  },
  {
    path: '/admin/datasets',
    icon: 'dataset',
    label: 'Data',
    groupId: 'site',
    order: 3,
  },
  {
    path: '/admin/money',
    icon: 'paid',
    label: 'Money',
    groupId: 'doing',
    order: 3,
  },
  {
    path: '/admin/orders',
    icon: 'order_approve',
    label: 'Orders',
    groupId: 'shop',
    order: 2,
  },
  {
    path: '/admin/coupons',
    icon: 'sell',
    label: 'Coupon',
    groupId: 'marketing',
    order: 4,
  },
  {
    path: '/admin/ppl',
    icon: 'face',
    label: 'People',
    groupId: 'doing',
    order: 2,
  },
  {
    path: '/admin/products',
    icon: 'inventory_2',
    label: 'Products',
    groupId: 'shop',
    order: 1,
  },
  {
    path: '/admin/soundboard',
    icon: 'sports_bar',
    label: 'Attention',
    groupId: 'extra',
    order: 1,
  },
  {
    path: '/admin/soundboard/schedule',
    icon: 'calendar_month',
    label: 'Time',
    groupId: 'doing',
    order: 2,
  },
  {
    path: '/admin/soundboard/pomodoro',
    icon: 'timer',
    label: 'Pomodoro',
    groupId: 'doing',
    order: 3,
  },
  {
    path: '/admin/source/importData',
    icon: 'upload_file',
    label: 'Import',
    groupId: 'extra',
    showOnSlim: false,
    order: 5,
  },
  {
    path: '/admin/studio',
    icon: 'view_in_ar',
    label: 'Studio3D',
    groupId: 'doing',
    showOnSlim: true,
    order: 0.5,
  },
  {
    path: '/admin/tasks',
    icon: 'task',
    label: 'Tasks',
    groupId: 'doing',
    showOnSlim: true,
    order: 4,
  },
  {
    path: '/admin/projects',
    icon: 'folder',
    label: 'Projects',
    groupId: 'doing',
    showOnSlim: false,
    order: 5,
  },
  {
    path: '/admin/things',
    icon: 'sunny',
    label: 'Things',
    groupId: 'extra',
    order: 4,
  },
  {
    path: '/admin/voice',
    icon: 'auto_detect_voice',
    label: 'Voice',
    groupId: 'extra',
    order: 5.5,
  },
];

const groups: string[] = ['marketing', 'shop', 'site', 'doing', 'extra'];
