export const icons = [
  {
    id: 'contacts',
    name: 'Contacts',
    iconName: 'people',
    order: 1,
  },
  {
    id: 'calendar',
    name: 'Calendar',
    iconName: 'calendar_month',
    order: 2,
  },
  {
    id: 'balance',
    name: 'Balance',
    iconName: 'balance',
    order: 3,
  },
  {
    id: 'finances',
    name: 'Finances',
    iconName: 'attach_money',
    order: 4,
  },
  {
    id: 'todos',
    name: 'Todos',
    iconName: 'task',
    order: 5,
  },
  {
    id: 'documents',
    name: 'Docs',
    iconName: 'description',
    order: 6,
  },
  {
    id: 'lists',
    name: 'Lists',
    iconName: 'notes',
    order: 7,
  },
  {
    id: 'events',
    name: 'Events',
    iconName: 'event',
    order: 8,
  },
  {
    id: 'express',
    name: 'Express',
    iconName: '360',
    order: 9,
  },
  {
    id: 'sales',
    name: 'Sales',
    iconName: 'point_of_sale',
    order: 10,
  },
  {
    id: 'books',
    name: 'Books',
    iconName: 'book',
    order: 11,
  },
  {
    id: 'movement',
    name: 'Movement',
    iconName: 'directions_bike',
    order: 12,
  },
  {
    id: 'post',
    name: 'Post',
    iconName: 'post_add',
    order: 13,
  },
  {
    id: 'mindfulness',
    name: 'Mindfulness',
    iconName: 'spa',
    order: 14,
  },
  {
    id: 'diy',
    name: 'DIY',
    iconName: 'build',
    order: 15,
  },
  {
    id: 'things',
    name: 'Things',
    iconName: 'editor_choice',
    order: 16,
  },
  {
    id: 'fun',
    name: 'Fun',
    iconName: 'sports_esports',
    order: 17,
  },
  {
    id: 'nature',
    name: 'Nature',
    iconName: 'nature_people',
    order: 18,
  },
];
