export const data = [
    {
        id: 'allLeads',
        title: 'All Leads',
        value: '4',
        mode: 'manual',
        clickEffect: 'nudge',
        journey: [],
        unit: 'number',
        href: '#',
    },
    {
        id: 'leadsInbox',
        title: 'Leads Inbox',
        value: '5',
        mode: 'manual',
        clickEffect: 'nudge',
        unit: 'number',
        journey: [],
        href: '#',
    },
    {
        id: 'totalClients',
        title: 'Total Clients',
        value: '10',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'nudge',
        journey: [
            {
                id: '1',
                value: 10,
                percent: 30,
            },
            {
                id: '2',
                value: 20,
                percent: 50,
            },
            {
                id: '3',
                value: 50,
                percent: 100,
            },
        ],
        href: '#',
    },
    {
        id: 'totalStars',
        title: 'Total Stars',
        value: '10',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'nudge',
        journey: [],
        href: '#',
    },
    {
        id: 'allContacts',
        title: 'All Contacts',
        value: '120',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'openTasks',
        title: 'Open Tasks',
        value: '10',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'nudge',
        journey: [],
        href: '#',
    },
    {
        id: 'closedTasks',
        title: 'Closed Tasks',
        value: '10',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'nudge',
        journey: [],
        href: '#',
    },
    {
        id: 'totalSales',
        title: 'Total Sales',
        value: '$ 1,000',
        mode: 'manual',
        unit: 'currency',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'knowledgeInbox',
        title: 'Knowledge Inbox',
        value: '$ 1,000',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'eventsToday',
        title: 'Events',
        value: '5 today',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'scheduleItems',
        title: 'Schedule',
        value: '5 items',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'monthlySales',
        title: 'Monthly Sales',
        value: '$ 1,000',
        mode: 'manual',
        unit: 'currency',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'marketingSpent',
        title: 'Marketing spent',
        value: '$ 1,000',
        mode: 'manual',
        unit: 'currency',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'marketingLeads',
        title: 'Marketing leads',
        value: '100',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'salesActions',
        title: 'Sales Actions',
        value: '80',
        mode: 'manual',
        unit: 'number',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
    {
        id: 'breaksDown',
        title: 'Breaks taken',
        value: '20min',
        mode: 'manual',
        unit: 'time',
        clickEffect: 'value',
        journey: [],
        href: '#',
    },
];
