export const itemStructure = `export type ILead = {
    id: string;
    title: string;
    startDate: string;
    leadType: ILeadType;
    status: ILeadStatus;
    statusDate: string;
    endDate?: string;
    description: string;
    personId: string;
    nextVisitDate: string;
    items: ILeadJournal[];
    worth?: number;
    percent?: number;
    isArchived?: boolean;
    isSuccessful?: boolean;
    isLost?: boolean;
    tags: string[];
    dataTags: string[];
};
`;
