export const avatars = [
  `Adam', american, deep, middle aged, male, narration`,
  `Antoni', american, well-rounded, young, male, narration`,
  `Arnold', american, crisp, middle aged, male, narration`,
  `Bella', american, soft, young, female, narration`,
  `Bill', american, strong, middle aged, male, documentary`,
  `Brian', british, mature, old, male, informative_educational`,
  `Callum', american, hoarse, middle aged, male, video games`,
  `Charlie', australian, casual, middle aged, male, conversational`,
  `Charlotte', english-swedish, seductive, middle aged, female, video games`,
  `Clyde', american, war veteran, middle aged, male, video games`,
  `Daniel', british, deep, middle aged, male, news presenter`,
  `Dave', british-essex, conversational, young, male, video games`,
  `Domi', american, strong, young, female, narration`,
  `Dorothy', british, pleasant, young, female, children's stories`,
  `Drew', american, well-rounded, middle aged, male, news`,
  `Ella', british, childish, young, female, narrative_story`,
  `Elli', american, emotional, young, female, narration`,
  `Emily', american, calm, young, female, meditation`,
  `Emma', british, calm, young, female, narrative_story`,
  `Ethan', american, young, male, ASMR, whisper`,
  `Fin', irish, sailor, old, male, video games`,
  `Freya', american, young, female, overhyped, video games`,
  `George', british, raspy, middle aged, male, narration`,
  `Gigi', american, childlish, young, female, animation`,
  `Giovanni', english-italian, foreigner, young, male, audiobook`,
  `Glinda', american, witch, middle aged, female, video games`,
  `Grace', american-southern, young, female, audiobook , gentle`,
  `Harry', american, anxious, young, male, video games`,
  `James', australian, calm , old, male, news`,
  `Jennifer', indian, old, female`,
  `Jeremy', american-irish, excited, young, male, narration`,
  `Jessie', american, raspy , old, male, video games`,
  `Johny', british, middle_aged, male`,
  `Joseph', british, middle aged, male, news, ground reporter`,
  `Josh', american, deep, young, male, narration`,
  `Knightley', british, deep, old, male, narrative_story`,
  `Liam', american, young, male, narration, neutral`,
  `Lily', british, raspy, middle aged, female, narration`,
  `Matilda', american, warm, young, female, audiobook`,
  `Matthew', british, middle aged, male, audiobook, calm`,
  `Michael', british, rough, middle_aged, male, narrative_story`,
  `Mimi', english-swedish, childish, young, female, animation`,
  `Nicole', american, whisper, young, female, audiobook`,
  `Paddington', british, deep, old, male, narrative_story`,
  `Patrick', american, shouty, middle aged, male, video games`,
  `Paul', american, ground reporter, middle aged, male, news`,
  `Rachel', american, calm, young, female, narration`,
  `Ryan', middle aged, soldier, american, male, audiobook`,
  `Sam', american, raspy, young, male, narration`,
  `Serena', american, pleasant, middle aged, female, interactive`,
  `Thomas', american, calm, young, male, meditation`,
  `Valentino', british, meditative, old, male, narrative_story`,
  `Victoria', british, young, female`,
];
