export const items = [
  {
    id: 'cta_contact',
    name: 'Contact',
    iconName: 'people',
    boardId: 'B-008',
    order: 1,
  },
  {
    id: 'cta_meeting',
    name: 'Meeting',
    iconName: 'calendar_month',
    boardId: 'B-009',
    order: 2,
  },
  {
    id: 'cta_reminder',
    name: 'Reminder',
    iconName: 'alarm',
    boardId: 'B-052',
    order: 3,
  },
  {
    id: 'cta_todo',
    name: 'Todo',
    iconName: 'task',
    boardId: 'B-012',
    order: 4,
  },
  {
    id: 'cta_document',
    name: 'Doc',
    iconName: 'description',
    boardId: 'B-013',
    order: 5,
  },
  {
    id: 'cta_list',
    name: 'List',
    iconName: 'notes',
    boardId: 'B-015',
    order: 6,
  },
  {
    id: 'cta_event',
    name: 'Event',
    iconName: 'event',
    boardId: 'B-016',
    order: 7,
  },
  {
    id: 'cta_read',
    name: 'Read',
    iconName: 'book',
    boardId: 'B-020',
    order: 8,
  },
  {
    id: 'cta_message',
    name: 'Message',
    iconName: 'post_add',
    boardId: 'B-022',
    order: 9,
  },
];
