name: app-settings publish

on:
    push:
        branches:
            - main
        paths:
            - apps/app-settings/**

jobs:
    publish:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org/'
                  scope: '@gdi'
            - name: Remove root package.json
              run: rm package.json
            - name: Cache node modules
              id: cache-npm
              uses: actions/cache@v3
              env:
                  cache-name: cache-node-modules
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-
            - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list
              working-directory: ./apps/app-settings
            - name: Install dependencies
              run: npm install
              working-directory: ./apps/app-settings
            - name: Build
              run: npm run build
              working-directory: ./apps/app-settings
            - uses: JS-DevTools/npm-publish@v1
              with:
                  package: ./apps/app-settings/package.json
                  token: ${{ secrets.NPM_TOKEN }}
                  access: public
