name: app-carts publish

on:
    push:
        branches:
            - main
        paths:
            - extra/apps/app-carts/**

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run build
              working-directory: extra/apps/app-carts/
            - run: npm publish
              working-directory: extra/apps/app-carts/
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
