name: gdi-web-editors publish

on:
    push:
        branches:
            - main
        paths:
            - packages/gdi-web-editors/**

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16
            - run: npm ci
            - run: npm run build
              working-directory: packages/gdi-web-editors/
            - run: npm publish
              working-directory: packages/gdi-web-editors/
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
