export const videoEffects = [
  {
    id: 'none',
    name: 'None',
    description: 'No effect applied',
    iconName: 'panorama_fish_eye',
  },
  {
    id: 'fade-in',
    name: 'Fade In',
    description: 'Gradually transition from black to video',
    iconName: 'brightness_5',
  },
  {
    id: 'fade-out',
    name: 'Fade Out',
    description: 'Gradually transition from video to black',
    iconName: 'brightness_6',
  },
  {
    id: 'blur',
    name: 'Blur',
    description: 'Apply a blur effect to the video',
    iconName: 'blur_on',
  },
  {
    id: 'sepia',
    name: 'Sepia',
    description: 'Give the video a sepia-toned look',
    iconName: 'palette',
  },
  {
    id: 'vintage',
    name: 'Vintage',
    description: 'Add a vintage filter to the video',
    iconName: 'style',
  },
  {
    id: 'zoom-in',
    name: 'Zoom In',
    description: 'Gradually zoom into the video',
    iconName: 'zoom_in',
  },
  {
    id: 'zoom-out',
    name: 'Zoom Out',
    description: 'Gradually zoom out from the video',
    iconName: 'zoom_out',
  },
  {
    id: 'rotate-left',
    name: 'Rotate Left',
    description: 'Rotate the video 90 degrees to the left',
    iconName: 'rotate_left',
  },
  {
    id: 'rotate-right',
    name: 'Rotate Right',
    description: 'Rotate the video 90 degrees to the right',
    iconName: 'rotate_right',
  },
  {
    id: 'mirror-horizontal',
    name: 'Mirror Horizontal',
    description: 'Mirror the video horizontally',
    iconName: 'flip',
  },
  {
    id: 'mirror-vertical',
    name: 'Mirror Vertical',
    description: 'Mirror the video vertically',
    iconName: 'flip_camera_android',
  },
  {
    id: 'invert-colors',
    name: 'Invert Colors',
    description: 'Invert the colors of the video',
    iconName: 'invert_colors',
  },
  {
    id: 'sharpen',
    name: 'Sharpen',
    description: 'Apply a sharpening filter to the video',
    iconName: 'adjust',
  },
  {
    id: 'greyscale',
    name: 'Greyscale',
    description: 'Convert the video to greyscale',
    iconName: 'filter_b_and_w',
  },
  {
    id: 'brightness',
    name: 'Brightness',
    description: 'Adjust the brightness of the video',
    iconName: 'wb_sunny',
  },
  {
    id: 'contrast',
    name: 'Contrast',
    description: 'Adjust the contrast of the video',
    iconName: 'wb_iridescent',
  },
  {
    id: 'saturation',
    name: 'Saturation',
    description: 'Adjust the color saturation of the video',
    iconName: 'colorize',
  },
  {
    id: 'ripple',
    name: 'Ripple',
    description: 'Apply a ripple distortion effect to the video',
    iconName: 'waves',
  },
  {
    id: 'glitch',
    name: 'Glitch',
    description: 'Create a glitchy visual effect on the video',
    iconName: 'signal_wifi_off',
  },
];
